# Generated by Django 4.2.30 on 2026-05-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('budget', '0002_alter_transaction_category_and_more'), ('budget', '0003_alter_transaction_category_and_more'), ('budget', '0004_alter_transaction_category_and_more')]

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Grocery', 'Grocery'), ('Eat-outs', 'Eat-outs'), ('Travel', 'Travel'), ('Household', 'Household'), ('Sport/Health', 'Sport/Health'), ('Rent+Utilities', 'Rent+Utilities'), ('Yaki/Nori', 'Yaki/Nori'), ('Transportation', 'Transportation'), ('Home', 'Home'), ('Work Income', 'Work Income'), ('Subscriptions', 'Subscriptions'), ('Cash', 'Cash'), ('Savings', 'Savings'), ('Other Income', 'Other Income'), ('From Savings', 'From Savings')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('USD', 'USD')], default='EUR', max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Presentment', 'Presentment'), ('Direct Debit', 'Direct Debit'), ('Debit Transfer', 'Debit Transfer'), ('Credit Transfer', 'Credit Transfer'), ('Presentment Refund', 'Presentment Refund')], max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Grocery', 'Grocery'), ('Eat-outs', 'Eat-outs'), ('Travel', 'Travel'), ('Household', 'Household'), ('Sport/Health', 'Sport/Health'), ('Rent+Utilities', 'Rent+Utilities'), ('Yaki/Nori', 'Yaki/Nori'), ('Transportation', 'Transportation'), ('Home', 'Home'), ('Work Income', 'Work Income'), ('Subscriptions', 'Subscriptions'), ('Cash', 'Cash'), ('Savings', 'Savings'), ('Other Income', 'Other Income'), ('From Savings', 'From Savings'), ('Coffee', 'Coffee'), ('Dining Out', 'Dining Out')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('USD', 'USD'), ('CHF', 'CHF'), ('SEK', 'SEK')], default='EUR', max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Presentment', 'Presentment'), ('Direct Debit', 'Direct Debit'), ('Debit Transfer', 'Debit Transfer'), ('Credit Transfer', 'Credit Transfer'), ('Presentment Refund', 'Presentment Refund'), ('Standing Order', 'Standing Order')], max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(blank=True, default='EUR', max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Type'),
        ),
    ]
