# Generated by Django 4.2.30 on 2026-06-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_transaction_options_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
