# Generated by Django 4.2.30 on 2026-05-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_reference', models.TextField(blank=True)),
                ('partner_iban', models.CharField(blank=True, max_length=64)),
                ('transaction_type', models.CharField(blank=True, max_length=64, verbose_name='Type')),
                ('account_name', models.CharField(blank=True, max_length=128)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('original_currency', models.CharField(blank=True, max_length=8)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-booking_date', '-id'],
            },
        ),
    ]
